### PR TITLE
Deprecate API

### PR DESCRIPTION
**Pull request by retaps**
Pass the API stuff to this page

### CODE REVIEW

**Comment by retaps** [comment]
Wait i forgot a file

**Comment by retaps** [comment]
Nevermind all good

**Review by Keanu73 — APPROVED** [review]

**Comment by Keanu73** [comment]
I'm satisfied, it loads fast & quite good - and handles network errors quite well

**Comment by Keanu73** [comment]
I'm satisfied, it loads fast & quite good - and handles network errors quite well

**Pull request merged**
